### ISSUE TITLE
Changing length error

### ISSUE THREAD

**Issue by WombleWoo7547** [ai/nanoid#273]
### This is the error:
```
RangeError [ERR_INVALID_OPT_VALUE]: The value "NaN" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:383:3)
    at random (/home/runner/nanoid/node_modules/nanoid/index.cjs:15:19)
    at nanoid (/home/runner/nanoid/node_modules/nanoid/index.cjs:66:15)
    at /home/runner/nanoid/index.js:3:13
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

```

### My code is very simple:
```
const { nanoid } = require('nanoid');

const str = nanoid({
	length: 25,
});

console.log(str);
```
#   

Note: I am using repl.it for my node projects.

**Comment by ai** [comment]
```diff
- const str = nanoid({
- 	length: 25,
- });
+ const str = nanoid(25);
```
