### ISSUE TITLE
Problem with typescript 

### ISSUE THREAD

**Issue by blacklyondev** [ai/nanoid#375]
When I try to generate an ID with the nanoid package in my typescript project I get the following error:

`const nanoid_1 = __importDefault(require("nanoid"));
                                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module $PATH/node_modules/nanoid/index.js from $PATH/dist/tools/id.js not supported.
Instead change the require of index.js in $PATH/dist/tools/id.js to a dynamic import() which is available in all CommonJS modules.

  code: 'ERR_REQUIRE_ESM'
}`

**Comment by dan-turner** [comment]
I am experiencing similar when trying to run tests via jest using ts-jest.  This worked prior to upgrading to version 3.

```
 FAIL  src/graphql/resolvers/mutations/createPurchase.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/dan/code/real/real-web/node_modules/nanoid/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { randomFillSync } from 'crypto'
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 2 | import { nanoid } from "nanoid";
        | ^
      3 |
      4 | import { createPurchase } from "./createPurchase";
      5 |

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (src/graphql/resolvers/mutations/createPurchase.spec.ts:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.847 s, estimated 7 s
```
