### ISSUE TITLE
Can this be used to convert existing bytes?

### ISSUE THREAD

**Issue by rightaway** [ai/nanoid#81]
If I already have an existing 16 bytes of a uuid, can I use nanoid to generate a shorter id from that (providing a given alphabet) and also ensuring an even distribution of generated ids? I suppose the generated id length would vary in that case so I suppose the even distribution wouldn't work?

**Comment by rightaway** [comment]
I get an error when nanoid calls `random(step)` in `nanoid/format`.

```
RangeError [ERR_OUT_OF_RANGE]: The value of "size" is out of range. It must be >= 0 && <= 2147483647. Received NaN
    at assertSize (internal/crypto/random.js:39:11)
    at randomBytes (internal/crypto/random.js:51:10)
```

**Comment by ai** [comment]
Can you show full code?

**Comment by rightaway** [comment]
I'm not sure I'm using this correctly, it's a Buffer of 16 bytes.

```js
crypto = require('crypto')
format(() => {
  return crypto.randomBytes(16)
}, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ', 25)
```

**Comment by ai** [comment]
You do not need `format` for it. Just use `nanoid/generate`.

You need `format` to replace random generator (you use standard generator here). I suggested you to use `format` to convert UUIDs to compact form.
